version: '3.7'
services:
  dynamodb:
    image: amazon/dynamodb-local:1.11.477
    ports:
    - '8770:8000'
    command: -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -delayTransientStatuses
  minio:
    image: minio/minio:RELEASE.2019-08-14T20-37-41Z
    environment:
      MINIO_ACCESS_KEY: user
      MINIO_SECRET_KEY: Sie9eiMe
    ports:
    - '8771:9000'
    command: minio server /data
